name: jordan
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.799072855617851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#87ace0'
    - '#d1ddf2'
    - '#161b21'
    - '#607e80'
    - '#2c3545'
  brandStrength: 0.1875
  lightness: 0.19413344888016582
  saturation: 0.5403289368841797
  rhythmicContrast: 0.8461669750977308
purpose: []
