name: jordan
favicon: null
layout_spectrum: 0.67726
typography_spectrum: 0.21112
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0b0c'
    - '#534720'
    - '#a9a290'
    - '#d5d2cd'
    - '#9c2228'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
