name: jordan
favicon: null
layout_spectrum: 0.22255
typography_spectrum: 0.73745
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#427196'
    - '#92a7c4'
    - '#202a34'
    - '#7a5d43'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
