name: jordan
favicon: null
layout_spectrum: 0.67726
typography_spectrum: 0.21112
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7da3cd'
    - '#000004'
    - '#fefefe'
    - '#59686f'
    - '#c4d1e3'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
