name: jordan
favicon: null
layout_spectrum: 0.67726
typography_spectrum: 0.21112
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8e97a7'
    - '#050507'
    - '#e4e9e5'
    - '#675e5f'
    - '#bbc2d1'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
